variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
  CMAKE_PREFIX_PATH: /opt/toolchains
  SCALENODE_CPU: 4
  SCALENODE_RAM: 8192
  SCALENODE_DISK: 40
  RENODE_REF: 5744a5482f7a83447ee31173c695200966313076

# Triggered for main pushes, schedules etc. and on MR creation or modification
.only_main_and_all_mrs: &only_main_and_all_mrs
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "main"
      - $CI_PIPELINE_SOURCE == "merge_request"

stages:
  - Build dependencies
  - Build
  - Test

Build Renode:
  image: debian:bookworm
  stage: Build dependencies
  <<: *only_main_and_all_mrs
  variables:
    SCALENODE_CPU: 6
    SCALENODE_DISK: 20
    SCALENODE_RAM: 10000
    GIT_STRATEGY: none # This job doesn't use any of the files from this repo, no need to clone it.
  before_get_sources:
    - |
      apt -qqy update &> /dev/null
      apt -qqy install git wget cmake gcc locales parallel ruby-standalone rpm libarchive-tools python3 python3-pip python3-venv &> /dev/null
      gem install fpm
      wget --tries=3 https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      dpkg -i packages-microsoft-prod.deb
      apt -qqy update &> /dev/null && apt -y install dotnet-sdk-8.0
  before_script:
    - |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade git+https://gitlab-ci-token:$CI_BUILD_TOKEN@dev.antmicro.com/git/renode-git-helper.git

    - |
      git clone https://gitlab-ci-token:$CI_BUILD_TOKEN@dev.antmicro.com/git/renode.git
      pushd renode
        git checkout origin/master
        renode-git-helper set-remotes -p --username gitlab-ci-token --password "$CI_BUILD_TOKEN"
        git submodule update --init --recursive
        git fetch --all
        git checkout $RENODE_REF
        git submodule update --init --recursive
      popd
  script:
    - |
      # Packages build
      pushd renode
        ./build.sh -pt --source-package --no-gui
      popd 
      # Copy package to artifacts
      mkdir -p artifacts/renode
      cp renode/output/packages/*.linux-portable.tar.gz artifacts/renode
  artifacts:
    paths:
      - artifacts/

Build SystemC:
  image: debian:12.5-slim
  stage: Build dependencies
  <<: *only_main_and_all_mrs
  before_get_sources:
    - apt-get -qqy update
    - apt-get install -qqy cmake clang git
  script:
    - mkdir -p build artifacts/systemc
    - |
      pushd build
        cmake ../systemc -DBUILD_SHARED_LIBS=OFF \
                         -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                         -DCMAKE_CXX_STANDARD=14 \
                         -DCMAKE_POLICY_VERSION_MINIMUM="3.5"
        cmake --build . -j $(nproc)
      popd
    - cp build/src/libsystemc.a artifacts/systemc
  artifacts:
    paths:
      - artifacts/

Build Zephyr Binaries:
  image: zephyrprojectrtos/ci:v0.28.2
  stage: Build dependencies
  <<: *only_main_and_all_mrs
  script:
    - west init -l .
    - west update
    - west zephyr-export
    - west packages pip --install

    - mkdir -p artifacts/zephyr_binaries

    - |
      for example in examples/*/zephyr; do
        example_name=$(echo $example | cut -f 2 -d '/')
        west build -p -b stm32f401_mini $example
        cp build/zephyr/zephyr.elf artifacts/zephyr_binaries/$example_name.elf
      done
  artifacts:
    paths:
      - artifacts/

Build Examples:
  image: debian:bookworm
  stage: Build
  <<: *only_main_and_all_mrs
  before_get_sources:
    - apt-get -qqy update
    - apt-get -qqy install clang cmake git wget
    - wget --tries=3 --progress=dot:giga https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - apt -qqy update &> /dev/null && apt -y install dotnet-runtime-8.0
  before_script:
    - mkdir -p /opt/renode
    - tar xf ./artifacts/renode/renode-*linux-portable.tar.gz -C /opt/renode --strip 1
  script:
    - mkdir -p build
    - mkdir -p artifacts/{example_binaries,test_binaries,shared_libs}

    - |
      pushd build
        cmake .. -DUSER_RENODE_DIR=/opt/renode \
                 -DUSER_SYSTEMC_INCLUDE_DIR=$(pwd)/../systemc/src \
                 -DUSER_SYSTEMC_LIB_DIR=$(pwd)/../artifacts/systemc \
                 -DCMAKE_CXX_STANDARD=14
        cmake --build . -j $(nproc)
      popd

    - |
      for example in examples/*/; do
        example_name="$(basename $example)"
        cp -v build/examples/$example_name/$example_name artifacts/example_binaries/x64-systemc--$example_name.elf
      done
    - |
      for test in tests/*/; do
        test_name="$(basename $test)"
        cp -v build/tests/$test_name/$test_name artifacts/test_binaries/x64-systemc--$test_name.elf
      done
    - |
      for example in examples-native/*/; do
        example_name="$(basename $example)"
        library_name="lib$(basename $example | tr '-' '_').so"
        cp -v build/examples-native/$example_name/$library_name artifacts/shared_libs/$library_name
      done
  artifacts:
    paths:
      - artifacts/

Test Examples:
  image: debian:bookworm
  stage: Test
  <<: *only_main_and_all_mrs
  dependencies:
    - Build Examples
    - Build Renode
  before_get_sources:
    - apt -qqy update &> /dev/null
    - apt -qqy install git clang wget cmake gcc python3 python3-pip python3-venv python3-dev locales parallel &> /dev/null
    - wget --tries=3 --progress=dot:giga https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - apt -qqy update &> /dev/null && apt -y install dotnet-runtime-8.0
  before_script:
    - |
      mkdir -p /opt/renode
      tar xf ./artifacts/renode/renode-*linux-portable.tar.gz -C /opt/renode --strip 1
      export PATH="$PATH:/opt/renode"

      renode --version
    - |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install -r /opt/renode/tests/requirements.txt
  script:
    - export PATH="$PATH:/opt/renode"
    - source venv/bin/activate

    - |
      for example in artifacts/example_binaries/*; do
        example_name="$(basename $example | sed -e 's/x64-systemc--//' -e 's/.elf//')"
        mkdir -p examples/$example_name/bin
        cp $example examples/$example_name/bin/$example_name
      done
    - |
      for test in artifacts/test_binaries/*; do
        test_name="$(basename $test | sed -e 's/x64-systemc--//' -e 's/.elf//')"
        mkdir -p tests/$test_name/bin
        cp $test tests/$test_name/bin/$test_name
      done
    - |
      for example in artifacts/shared_libs/*; do
        # tranform /bar/foo/libfoo_bar.so to foo-bar
        example_name="$(basename $example | sed -e 's/\.so$//' -e 's/^lib//' | tr '_' '-')"
        mkdir -p examples-native/$example_name/build
        cp $example examples-native/$example_name/build
      done

    - |
      pushd examples-native
        renode-test -t all_examples.yaml
      popd

    - |
      pushd examples
        renode-test -t all_examples.yaml
      popd

    - |
      pushd tests
        renode-test -t all_tests.yaml
      popd
