variables:
  WEST_VERSION: 1.2.0
  ZEPHYR_SDK_VERSION: 0.16.5-1
  ZEPHYR_SDK_BASENAME: zephyr-sdk-${ZEPHYR_SDK_VERSION}
  ZEPHYR_SDK_FILENAME: zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz
  ZEPHYR_VERSION: d0ae1a8b1057c0a8b510860d1cbdbb1cb79f2411

stages:
  - build_dependencies
  - build
  - test

build_systemc:
  image: antmicro/renode:nightly
  stage: build_dependencies
  script:
    - apt-get -qqy update && apt-get install -qqy cmake clang git
    - git submodule update --init
    - pushd systemc
    - mkdir -p build
    - pushd build
    - cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_STANDARD=14
    - make -j
    - popd 
    - popd
    - mkdir -p artifacts/systemc
    - cp systemc/build/src/libsystemc.a artifacts/systemc
  artifacts:
    paths:
      - artifacts/

build_zephyr_binaries:
  image: debian:12.5-slim
  stage: build_dependencies
  script:
    - apt-get -qqy update && apt-get install -qqy wget python3-pip python3-venv cmake git ninja-build
    - python3 -m venv venv && source venv/bin/activate
    - pip3 install west==${WEST_VERSION}
    - wget --no-verbose https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZEPHYR_SDK_VERSION}/${ZEPHYR_SDK_FILENAME} && tar xf ${ZEPHYR_SDK_FILENAME} && pushd ${ZEPHYR_SDK_BASENAME} && ./setup.sh -t all -c && popd && export ZEPHYR_SDK_INSTALL_DIR=$(pwd)/${ZEPHYR_SDK_BASENAME}
    - west init zephyrproject
    - pushd zephyrproject/zephyr
    - git checkout ${ZEPHYR_VERSION} && west update
    - pip3 install -r scripts/requirements.txt
    - west update
    - popd
    - mkdir -p artifacts/zephyr_binaries
    - for i in `find examples -name "zephyr"`;
      do
        EXAMPLE_NAME="$(echo $i | sed -e "s/examples\///" -e "s/\/zephyr//")";
        mkdir -p examples/$EXAMPLE_NAME/bin;
        pushd zephyrproject/zephyr;
        west build -b stm32f401_mini ../../examples/$EXAMPLE_NAME/zephyr;
        cp build/zephyr/zephyr.elf ../../examples/$EXAMPLE_NAME/bin/$EXAMPLE_NAME.elf;
        cp build/zephyr/zephyr.elf ../../artifacts/zephyr_binaries/$EXAMPLE_NAME.elf;
        rm -rf build/;
        popd;
      done
  artifacts:
    paths:
      - artifacts/

build_examples:
  image: antmicro/renode:nightly
  stage: build
  script:
    - apt -qqy update
    - apt -qqy install clang cmake git
    - git submodule update --init
    - mkdir -p build
    - pushd build
    - cmake .. -DUSER_RENODE_DIR=/opt/renode -DUSER_SYSTEMC_INCLUDE_DIR=$(pwd)/../systemc/src -DUSER_SYSTEMC_LIB_DIR=$(pwd)/../artifacts/systemc -DCMAKE_CXX_STANDARD=14
    - make -j
    - popd
    - mkdir -p artifacts/example_binaries
    - mkdir -p artifacts/test_binaries
    - for i in examples/*/;
      do 
        EXAMPLE_NAME="$(basename $i)";
        cp examples/$EXAMPLE_NAME/bin/$EXAMPLE_NAME artifacts/example_binaries/x64-systemc--$EXAMPLE_NAME.elf;
      done
    - for i in tests/*/;
      do 
        TEST_NAME="$(basename $i)";
        cp tests/$TEST_NAME/bin/$TEST_NAME artifacts/test_binaries/x64-systemc--$TEST_NAME.elf;
      done
  artifacts:
    paths:
      - artifacts/

test_examples:
  image: antmicro/renode:nightly
  stage: test
  dependencies:
    - build_examples
  script:
    - apt -qqy update
    - apt -qqy install libsystemc libsystemc-dev
    - for i in artifacts/example_binaries/*;
      do
        EXAMPLE_NAME="$(basename $i | sed -e 's/x64-systemc--//' -e 's/.elf//')";
        mkdir -p examples/$EXAMPLE_NAME/bin;
        cp $i examples/$EXAMPLE_NAME/bin/$EXAMPLE_NAME;
      done
    - pushd examples
    - renode-test -t all_examples.yaml
    - popd
    - for i in artifacts/test_binaries/*;
      do
        TEST_NAME="$(basename $i | sed -e 's/x64-systemc--//' -e 's/.elf//')";
        mkdir -p tests/$TEST_NAME/bin;
        cp $i tests/$TEST_NAME/bin/$TEST_NAME;
      done
    - pushd tests
    - renode-test -t all_tests.yaml
    - popd
