variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
  CMAKE_PREFIX_PATH: /opt/toolchains
  SCALENODE_CPU: 4
  SCALENODE_RAM: 8192
  SCALENODE_DISK: 40

stages:
  - Build dependencies
  - Build
  - Test

Build SystemC:
  image: debian:12.5-slim
  stage: Build dependencies
  before_get_sources:
    - apt-get -qqy update
    - apt-get install -qqy cmake clang git
  script:
    - mkdir -p build artifacts/systemc
    - |
      pushd build
        cmake ../systemc -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_STANDARD=14
        make -j $(nproc)
      popd
    - cp build/src/libsystemc.a artifacts/systemc
  artifacts:
    paths:
      - artifacts/

Build Zephyr Binaries:
  image: zephyrprojectrtos/ci:v0.28.2
  stage: Build dependencies
  script:
    - west init -l .
    - west update
    - west zephyr-export
    - west packages pip --install

    - mkdir -p artifacts/zephyr_binaries

    - |
      for example in examples/*/zephyr; do
        example_name=$(echo $example | cut -f 2 -d '/')
        west build -p -b stm32f401_mini $example
        cp build/zephyr/zephyr.elf artifacts/zephyr_binaries/$example_name.elf
      done
  artifacts:
    paths:
      - artifacts/

Build Examples:
  image: antmicro/renode:nightly-dotnet
  stage: Build
  before_get_sources:
    - apt-get -qqy update
    - apt-get -qqy install clang cmake git
  script:
    - mkdir -p build
    - |
      pushd build
        cmake .. -DUSER_RENODE_DIR=/opt/renode -DUSER_SYSTEMC_INCLUDE_DIR=$(pwd)/../systemc/src -DUSER_SYSTEMC_LIB_DIR=$(pwd)/../artifacts/systemc -DCMAKE_CXX_STANDARD=14
        make -j $(nproc)
      popd

    - mkdir -p artifacts/example_binaries artifacts/test_binaries
    - |
      for example in examples/*/; do
        example_name="$(basename $example)"
        cp examples/$example_name/bin/$example_name artifacts/example_binaries/x64-systemc--$example_name.elf
      done
    - |
      for test in tests/*/; do
        test_name="$(basename $test)"
        cp tests/$test_name/bin/$test_name artifacts/test_binaries/x64-systemc--$test_name.elf
      done
  artifacts:
    paths:
      - artifacts/

Test Examples:
  image: antmicro/renode:nightly-dotnet
  stage: Test
  dependencies:
    - Build Examples
  before_get_sources:
    - apt-get -qqy update
    - apt-get -qqy install libsystemc libsystemc-dev
  script:
    - |
      for example in artifacts/example_binaries/*; do
        example_name="$(basename $example | sed -e 's/x64-systemc--//' -e 's/.elf//')"
        mkdir -p examples/$example_name/bin
        cp $example examples/$example_name/bin/$example_name
      done
    - |
      for test in artifacts/test_binaries/*; do
        test_name="$(basename $test | sed -e 's/x64-systemc--//' -e 's/.elf//')"
        mkdir -p tests/$test_name/bin
        cp $test tests/$test_name/bin/$test_name
      done

    - |
      pushd examples
        renode-test -t all_examples.yaml
      popd

    - |
      pushd tests
        renode-test -t all_tests.yaml
      popd
